name: dsa
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.3
  connectivity_plus: ^7.0.0
  http: ^1.6.0
  fluttertoast: ^9.0.0
  get_storage: ^2.1.1
  file_picker: ^10.3.8
  http_parser: ^4.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  fl_chart: ^1.1.1
  dio: ^5.9.0
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.3.0
  path_provider: ^2.1.5
  url_launcher: ^6.3.2

dev_dependencies:
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^6.0.0

flutter:

  
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
    - family: helveticaLight
      fonts:
        - asset: assets/fonts/HelveticaNeue-Light.otf  
    - family: helveticaMedium
      fonts:
        - asset: assets/fonts/HelveticaNeue-Medium.otf 
